resolver: nightly-2019-09-16
packages:
- .
extra-deps:
- haskell-lsp-0.18.0.0
- haskell-lsp-types-0.18.0.0
- lsp-test-0.8.2.0
- github: mpickering/hie-bios
  commit: 32c70fe232cfa6186c7e333205ec4ba103b8ad19
nix:
  packages: [zlib]
